Create table ACCOUNT_MASTER(ACCOUNT_MASTER_ID INTEGER (10) NOT NULL PRIMARY KEY, CONTACT_ID INTEGER (10) NOT NULL, ACCOUNT_REF_TYPE_ID INTEGER (5) NOT NULL, BALANCE FLOAT(12,2), IS_CLOSED BOOLEAN, ACCOUNT_CREATED_DATE TIMESTAMP, ACCOUNT_CLOSED_DATE TIMESTAMP);

CREATE TABLE ACCOUNT_REF_TYPE(ACCOUNT_REF_TYPE_ID CHAR(5), DESCRIPTION CHAR(25), ACCOUNT_TYPE_NAME CHAR(25));

CREATE TABLE CONTACT_MASTER(CONTACT_MASTER_ID INTEGER (10) NOT NULL PRIMARY KEY, FIRST_NAME CHAR(25) NOT NULL, LAST_NAME CHAR(25) NOT NULL, MIDDLE_INIITIAL CHAR(1), SUFFIX CHAR(3), HONORIFIC CHAR(4), MAILING_ADDRESS_ID INTEGER (10) NOT NULL, BILL_TO_ADDRESS_ID INTEGER (10), HOME_PHONE_NUMBER CHAR(12), WORK_PHONE_NUMBER CHAR(12), EMAIL_ADDRESS CHAR(75), DOB DATE NOT NULL);

ALTER TABLE ACCOUNT_MASTER ADD CONSTRAINT fk_ACCTCON FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT_MASTER(CONTACT_MASTER_ID);

CREATE TABLE ADDRESS_MASTER(ADDRESS_MASTER_ID INTEGER (10) NOT NULL PRIMARY KEY, ADDRESS_REF_TYPE_ID INTEGER(5), ADDRESS_NUMBER CHAR(10), STREET_NAME CHAR(50), ROAD_TYPE CHAR(5), ADDRESS_LINE2 CHAR(25), ADDRESS_LINE3 CHAR(25), CITY CHAR(50), STATE_CODE CHAR(2), ZIP_CODE CHAR(10), COUNTRY CHAR(2));
CREATE TABLE ADDRESS_REF_TYPE(ADDRESS_REF_TYPE_ID CHAR(5), DESCRIPTION CHAR(25), ADDRESS_TYPE_NAME CHAR(25));

ALTER TABLE CONTACT_MASTER ADD CONSTRAINT fk_CONTADD FOREIGN KEY (MAILING_ADDRESS_ID) REFERENCES ADDRESS_MASTER(ADDRESS_MASTER_ID);

CREATE TABLE CREDIT_CARD_MASTER(CC_MASTER_ID INTEGER (10) NOT NULL PRIMARY KEY, CC_NUMBER CHAR(16) NOT NULL, ISSUER CHAR(10), CONTACT_ID INTEGER (10) NOT NULL, ACCOUNT_MASTER_ID INTEGER (10) NOT NULL, CC_TYPE_REF_ID INTEGER(5), ACTIVITY_HISTORY_MASTER_ID BIGINT (20), IS_ACTIVE BOOLEAN, EXPIRATION_DATE CHAR(5), SECURITY_CODE CHAR(4), PIN CHAR(10), CC_STATUS_REF_ID INTEGER(5), ACTIVATION_DATE DATETIME NOT NULL, CLOSED_DATE DATETIME);

CREATE TABLE CREDIT_CARD_TYPE_REF(CC_TYPE_REF_ID INTEGER(5), CC_TYPE_REF_NAME CHAR(25), DESCRIPTION CHAR(25));
CREATE TABLE CREDIT_CARD_STATUS_REF(CC_STATUS_REF_ID INTEGER(5), CC_STATUS_REF_NAME CHAR(25), DESCRIPTION CHAR(25));

ALTER TABLE CREDIT_CARD_MASTER ADD CONSTRAINT fk_CCCONT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT_MASTER(CONTACT_MASTER_ID);
ALTER TABLE CREDIT_CARD_MASTER ADD CONSTRAINT fk_CCACCT FOREIGN KEY (ACCOUNT_MASTER_ID) REFERENCES ACCOUNT_MASTER(ACCOUNT_MASTER_ID);

CREATE TABLE ACTIVITY_HISTORY_MASTER(ACTIVITY_HISTORY_MASTER_ID BIGINT (20) NOT NULL PRIMARY KEY, CC_MASTER_ID INTEGER (10) NOT NULL, ACTIVITY_TYPE_REF_ID INTEGER (5), AMOUNT FLOAT(6, 2), ACTIVITY_DATE TIMESTAMP NOT NULL, ATM_LOCATION_MASTER_ID INTEGER(10));

CREATE TABLE ACTIVITY_TYPE_REF (ACTIVITY_TYPE_REF_ID INTEGER (5), NAME CHAR(25), DESCRIPTION CHAR(50));

ALTER TABLE ACTIVITY_HISTORY_MASTER ADD CONSTRAINT fk_ACTCC FOREIGN KEY (CC_MASTER_ID) REFERENCES CREDIT_CARD_MASTER(CC_MASTER_ID);

CREATE TABLE ATM_LOCATION_MASTER(BRANCH_MASTER_ID INTEGER (10) NOT NULL PRIMARY KEY, ADDRESS_MASTER_ID INTEGER (10) NOT NULL, DENOMINATION INT (2));


INSERT INTO ACCOUNT_REF_TYPE(ACCOUNT_REF_TYPE_ID, DESCRIPTION, ACCOUNT_TYPE_NAME) VALUES (1, 'Checking', 'CHK');

INSERT INTO CREDIT_CARD_TYPE_REF(CC_TYPE_REF_ID, CC_TYPE_REF_NAME, DESCRIPTION) VALUES (1, 'DEBIT', 'Debit Card');

INSERT INTO CREDIT_CARD_STATUS_REF(CC_STATUS_REF_ID, CC_STATUS_REF_NAME, DESCRIPTION) VALUES (0, 'ACTIVE', 'Active, no alerts');

INSERT INTO ADDRESS_REF_TYPE(ADDRESS_REF_TYPE_ID, DESCRIPTION, ADDRESS_TYPE_NAME) VALUES (1, 'PERMANANT ADDRESS', 'PERM');
INSERT INTO ADDRESS_REF_TYPE(ADDRESS_REF_TYPE_ID, DESCRIPTION, ADDRESS_TYPE_NAME) VALUES (0, 'BRANCH LOCATION', 'BRAN');

INSERT INTO ACTIVITY_TYPE_REF (ACTIVITY_TYPE_REF_ID, NAME, DESCRIPTION) VALUES (0, 'BALANCE', 'BALANCE INQUIRY - NO AFFECT ON BALANCE');
INSERT INTO ACTIVITY_TYPE_REF (ACTIVITY_TYPE_REF_ID, NAME, DESCRIPTION) VALUES (1, 'WITHDRAWL', 'WITHDRAWL - LOWERS EXISTING BALANCE');
INSERT INTO ACTIVITY_TYPE_REF (ACTIVITY_TYPE_REF_ID, NAME, DESCRIPTION) VALUES (2, 'DEPOSIT', 'DEPOSIT - INCREASES EXISTING BALANCE');

INSERT INTO ADDRESS_MASTER(ADDRESS_MASTER_ID, ADDRESS_REF_TYPE_ID, ADDRESS_NUMBER, STREET_NAME, ROAD_TYPE, CITY, STATE_CODE, ZIP_CODE, COUNTRY) VALUES (1, 1, '15041', 'BABBLING BROOK', 'DR', 'AUSTIN', 'TX', '78728', 'US');
INSERT INTO ADDRESS_MASTER(ADDRESS_MASTER_ID, ADDRESS_REF_TYPE_ID, ADDRESS_NUMBER, STREET_NAME, ROAD_TYPE, CITY, STATE_CODE, ZIP_CODE, COUNTRY) VALUES (2, 0, '123', 'MAIN', 'ST', 'AUSTIN', 'TX', '78758', 'US');

INSERT INTO ATM_LOCATION_MASTER(BRANCH_MASTER_ID, ADDRESS_MASTER_ID, DENOMINATION) values (1, 2, 20);

INSERT INTO CONTACT_MASTER(CONTACT_MASTER_ID, FIRST_NAME, LAST_NAME, MIDDLE_INIITIAL, HONORIFIC, MAILING_ADDRESS_ID, BILL_TO_ADDRESS_ID, HOME_PHONE_NUMBER, WORK_PHONE_NUMBER, EMAIL_ADDRESS, DOB) VALUES (1, 'DAVID', 'WHITLOCK', 'W', 'MR', 1, 1, '512-762-7448', 'XXX-XXX-XXXX', 'dwtx75@yahoo.com', '1975-06-15');

INSERT INTO ACCOUNT_MASTER(ACCOUNT_MASTER_ID, CONTACT_ID, ACCOUNT_REF_TYPE_ID, BALANCE, IS_CLOSED, ACCOUNT_CREATED_DATE) VALUES (1, 1, 1, 130.24, false, '2015-09-25 18:30:00');

INSERT INTO CREDIT_CARD_MASTER(CC_MASTER_ID, CC_NUMBER, ISSUER, CONTACT_ID, CC_TYPE_REF_ID, IS_ACTIVE, EXPIRATION_DATE, SECURITY_CODE, PIN, CC_STATUS_REF_ID, ACTIVATION_DATE, ACCOUNT_MASTER_ID) VALUES (1, 'XXXXYYYYZZZZAAAA', 'VISA', 1, 1, TRUE, '09/16', '123', '1234', 0, '2015-09-25 18:30:00', 1);

INSERT INTO ACTIVITY_HISTORY_MASTER(ACTIVITY_HISTORY_MASTER_ID, CC_MASTER_ID, ACTIVITY_TYPE_REF_ID, AMOUNT, ACTIVITY_DATE, ATM_LOCATION_MASTER_ID) values (1, 1, 2. 50.25, '2015-09-25 18:30:00', 1);